[RESEAU]
; Probabilité que chaque envoi UDP réussisse (1.0 = aucune perte, 0.7 = 30% de perte)
fiabilite = 0.95

; Taux de corruption des segments reçus (0.02 = 2% des segments reçus sont altérés)
taux_corruption = 0.02

; Délai d'attente maximal (secondes) avant retransmission d'un bloc non acquitté
timeout = 3.0
max_reprises = 5

[CONNEXION]
; Taille maximale proposée (en octets) pour les données 
; MSS = Maximum Segment Size
client_mss_propose = 1024
serveur_mss_propose = 1024

; Taille de fenêtre proposée 
n_propose = 4

[SERVEUR]
; Adresse IP d'écoute du serveur 
host = 127.0.0.1
; Port d'écoute du serveur
port = 4242

; Dossier de sauvegarde des fichiers reçus
dossier_sauvegardes = sauvegardes

; Dossier contenant les fichiers disponibles pour le client
dossier_fichiers = tests